# Generated by Django 2.2.4 on 2019-12-17 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycomment',
            name='email',
        ),
    ]
