# Generated by Django 3.0.2 on 2020-03-01 18:31

from django.db import migrations
import djbyexblog.app_posts.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_posts', '0002_remove_mycomment_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='order',
            field=djbyexblog.app_posts.fields.OrderField(blank=True),
        ),
    ]
